export const SymbolicDistroIcons = [
    { PATH: '/Resources/apple-icon-symbolic.svg' }, // Apple (Wackintosh) (index 0)
    { PATH: 'start-here-symbolic' },                 // Default (index 1)
    { PATH: '/Resources/fedora-logo-symbolic.svg' }, // Fedora (index 2)
    { PATH: '/Resources/debian-logo-symbolic.svg' }, // Debian (index 3)
    { PATH: '/Resources/manjaro-logo-symbolic.svg' },// Manjaro (index 4)
    { PATH: '/Resources/pop-os-logo-symbolic.svg' }, // Pop!_OS (index 5)
    { PATH: '/Resources/ubuntu-logo-symbolic.svg' }, // Ubuntu (index 6)
    { PATH: '/Resources/arch-logo-symbolic.svg' },   // Arch Linux (index 7)
    { PATH: '/Resources/opensuse-logo-symbolic.svg' },// openSUSE (index 8)
    { PATH: '/Resources/raspbian-logo-symbolic.svg' },// Raspbian (index 9)
    { PATH: '/Resources/kali-linux-logo-symbolic.svg' },// Kali Linux (index 10)
    { PATH: '/Resources/pureos-logo-symbolic.svg' },  // PureOS (index 11)
    { PATH: '/Resources/solus-logo-symbolic.svg' },   // Solus (index 12)
    { PATH: '/Resources/budgie-logo-symbolic.svg' },  // Budgie (index 13)
    { PATH: '/Resources/gentoo-logo-symbolic.svg' },  // Gentoo (index 14)
    { PATH: '/Resources/mx-logo-symbolic.svg' },      // MX Linux (index 15)
    { PATH: '/Resources/redhat-logo-symbolic.svg' },  // Red Hat (index 16)
    { PATH: '/Resources/voyager-logo-symbolic.svg' },  // Voyager (index 17)
    { PATH: '/Resources/garuda-logo-symbolic.svg' },  // Garuda (index 18)
    { PATH: '/Resources/freebsd-logo-symbolic.svg' }, // FreeBSD (index 19)
    { PATH: '/Resources/tux-logo-symbolic.svg' },     // Tux (Linux) (index 20)
    { PATH: '/Resources/rockylinux-logo-symbolic.svg' },// Rocky Linux (index 21)
    { PATH: '/Resources/endeavouros_logo-symbolic.svg' },// EndeavourOS (index 22)
    { PATH: '/Resources/almalinux-logo-symbolic.svg' },// AlmaLinux (index 23)
    { PATH: '/Resources/nixos-logo-symbolic.svg' },   // NixOS (index 24)
    { PATH: '/Resources/shastraos-logo-symbolic.svg' },// ShastraOS (index 25)
    { PATH: '/Resources/asahilinux-logo-symbolic.svg' },// Asahi Linux (index 26)
    { PATH: '/Resources/zorin-logo-symbolic.svg' },   // Zorin OS (index 27)
    { PATH: '/Resources/void-logo-symbolic.svg' },    // Void Linux (index 28)
    { PATH: '/Resources/nobara-logo-symbolic.svg' },  // Nobara (index 29)
    { PATH: '/Resources/steam-deck-logo-symbolic.svg' },// Steam Deck (index 30)
    { PATH: '/Resources/ublue-logo-symbolic.svg' },   // Ublue (index 31)
    { PATH: '/Resources/centos-logo-symbolic.svg' },  // CentOS (index 32)
    { PATH: '/Resources/cachyos-logo-symbolic.svg' },  // CachyOS (index 33)
];

export const ColouredDistroIcons = [
    { PATH: '/Resources/apple-icon-symbolic.svg' }, // Apple (Wackintosh) (index 0)
    { PATH: 'start-here-symbolic' },                 // Default (index 1)
    { PATH: '/Resources/fedora-logo.svg' },          // Fedora (index 2)
    { PATH: '/Resources/debian-logo.svg' },          // Debian (index 3)
    { PATH: '/Resources/manjaro-logo.svg' },         // Manjaro (index 4)
    { PATH: '/Resources/pop-os-logo.svg' },          // Pop!_OS (index 5)
    { PATH: '/Resources/ubuntu-logo.svg' },          // Ubuntu (index 6)
    { PATH: '/Resources/arch-logo.svg' },            // Arch Linux (index 7)
    { PATH: '/Resources/opensuse-logo.svg' },         // openSUSE (index 8)
    { PATH: '/Resources/raspbian-logo-symbolic.svg' },// Raspbian fallback (index 9)
    { PATH: '/Resources/kali-linux-logo.svg' },      // Kali Linux (index 10)
    { PATH: '/Resources/pureos-logo-symbolic.svg' },  // PureOS fallback (index 11)
    { PATH: '/Resources/solus-logo.svg' },           // Solus (index 12)
    { PATH: '/Resources/budgie-logo-symbolic.svg' },  // Budgie fallback (index 13)
    { PATH: '/Resources/gentoo-logo.svg' },          // Gentoo (index 14)
    { PATH: '/Resources/mx-logo-symbolic.svg' },      // MX Linux fallback (index 15)
    { PATH: '/Resources/redhat-logo.svg' },          // Red Hat (index 16)
    { PATH: '/Resources/voyager-logo-symbolic.svg' },  // Voyager fallback (index 17)
    { PATH: '/Resources/garuda-logo-symbolic.svg' },  // Garuda fallback (index 18)
    { PATH: '/Resources/freebsd-logo.svg' },         // FreeBSD (index 19)
    { PATH: '/Resources/tux-logo.svg' },             // Tux (Linux) (index 20)
    { PATH: '/Resources/rockylinux-logo.svg' },      // Rocky Linux (index 21)
    { PATH: '/Resources/endeavouros_logo.svg' },     // EndeavourOS (index 22)
    { PATH: '/Resources/almalinux-logo.svg' },       // AlmaLinux (index 23)
    { PATH: '/Resources/nixos-logo.svg' },          // NixOS (index 24)
    { PATH: '/Resources/shastraos-logo.svg' },       // ShastraOS (index 25)
    { PATH: '/Resources/asahilinux-logo.svg' },      // Asahi Linux (index 26)
    { PATH: '/Resources/zorin-logo.svg' },           // Zorin OS (index 27)
    { PATH: '/Resources/void-logo.svg' },            // Void Linux (index 28)
    { PATH: '/Resources/nobara-logo-symbolic.svg' },  // Nobara fallback (index 29)
    { PATH: '/Resources/steam-deck-logo.svg' },      // Steam Deck (index 30)
    { PATH: '/Resources/ublue-logo.svg' },           // Ublue (index 31)
    { PATH: '/Resources/centos-logo.svg' },          // CentOS (index 32)
    { PATH: '/Resources/cachyos-logo.svg' },         // CachyOS (index 33)
];
